# home-manager configuration, wired into the system flake so a single
# `nixos-rebuild switch` deploys both the system and per-user ($HOME) state.
{ inputs, ... }:

{
  imports = [ inputs.home-manager.nixosModules.home-manager ];

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; };
    # Back up (not clobber) any pre-existing files home-manager takes over,
    # e.g. Hyprland's autogenerated hyprland.lua on first activation.
    backupFileExtension = "hm-bak";

    users.stivce = {
      home.username = "stivce";
      home.homeDirectory = "/home/stivce";
      # Matches the system stateVersion; do not bump on upgrades.
      home.stateVersion = "26.05";

      # The wallpaper repo (github.com/st1vc3/wallpaper), pinned as a flake
      # input, symlinked into ~/Pictures/wallpapers. Updating it is a
      # `nix flake update wallpapers` + rebuild - no manual git clone.
      home.file."Pictures/wallpapers".source = inputs.wallpapers;

      # Wallpaper-setter script, deployed to ~/Scripts/set-wallpaper.sh.
      home.file."Scripts/set-wallpaper.sh" = {
        source = ./scripts/set-wallpaper.sh;
        executable = true;
      };

      # Hyprland + hyprlock/hypridle configs, deployed to ~/.config/hypr/.
      # Adapted for NixOS (pipewire via systemd socket activation, polkit
      # agent via its systemd user unit).
      xdg.configFile = {
        "hypr/hyprland.lua".source = ./config/hypr/hyprland.lua;
        "hypr/hypridle.conf".source = ./config/hypr/hypridle.conf;
        "hypr/hyprlock.conf".source = ./config/hypr/hyprlock.conf;
        "hypr/hyprlock-colors.conf".source = ./config/hypr/hyprlock-colors.conf;
        "hypr/start-hyprlock" = {
          source = ./config/hypr/start-hyprlock;
          executable = true;
        };

        # Waybar bar + stylesheet (default config, matched to the palette).
        "waybar/config.jsonc".source = ./config/waybar/config.jsonc;
        "waybar/style.css".source = ./config/waybar/style.css;
      };
    };
  };
}
