# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# Sane defaults
setopt AUTO_CD
setopt CORRECT

# Completion
autoload -Uz compinit && compinit
